services:
  app:
    image: ghcr.io/cannoi/family-tasks:16e662b747eabbfdb77ac54b1b9966acfe73e8df
    restart: unless-stopped
    labels:
      pi.ui.primary: "true"
    ports:
      - "127.0.0.1:18152:8080"
    environment:
      - PORT=8080
